-- CONSULTA 1: Recuperar todos os pedidos feitos na pizzaria com detalhes de cliente e produto
SELECT PV.DATA_PEDIDO, PV.VLR_PEDIDO_VENDA, C.NOME AS NOME_CLIENTE, 
       V.NOME AS NOME_VENDEDOR, FP.DES_FORMA_PAGAMENTO, P.NOME AS NOME_PRODUTO, 
       TP.DES_TIPO_PRODUTO
FROM PEDIDO_VENDA PV
INNER JOIN CLIENTE C ON C.COD_CLIENTE = PV.COD_CLIENTE 
INNER JOIN VENDEDOR V ON V.COD_VENDEDOR = PV.COD_VENDEDOR
INNER JOIN FORMA_PAGAMENTO FP ON FP.COD_FORMA_PAGAMENTO = PV.COD_FORMA_PAGAMENTO
INNER JOIN ITEM_PEDIDO_VENDA IPV ON IPV.COD_PEDIDO_VENDA = PV.COD_PEDIDO_VENDA
INNER JOIN PRODUTO P ON P.COD_PRODUTO = IPV.COD_PRODUTO
INNER JOIN TIPO_PRODUTO TP ON TP.COD_TIPO_PRODUTO = P.COD_TIPO_PRODUTO;

-- CONSULTA 2: Recuperar todos os pedidos com seus status e informações de pagamento
SELECT PV.DATA_PEDIDO, SP.STATUS_PEDIDO, SP.STATUS_PAGAMENTO
FROM PEDIDO_VENDA PV
INNER JOIN SITUACAO_PEDIDO SP ON SP.COD_SITUACAO_PEDIDO = PV.COD_SITUACAO_PEDIDO;

-- CONSULTA 3: Recuperar todas as cotações de produtos com detalhes do fornecedor
SELECT C.COD_COTACAO, C.VLR_COTACAO, C.UNIDADE_MEDIDA, P.NOME AS NOME_PRODUTO, F.NOME AS NOME_FORNECEDOR
FROM COTACAO C
INNER JOIN PRODUTO P ON P.COD_PRODUTO = C.COD_PRODUTO
INNER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = C.COD_FORNECEDOR;

-- CONSULTA 4: Recuperar todas as compras feitas com detalhes de produtos e fornecedores
SELECT PC.COD_PEDIDO_COMPRA, PC.VLR_PEDIDO_COMPRA, F.NOME AS NOME_FORNECEDOR, 
       IPC.QTD_ITEM_PEDIDO_COMPRA, P.NOME AS NOME_PRODUTO
FROM PEDIDO_COMPRA PC
INNER JOIN FORNECEDOR F ON F.COD_FORNECEDOR = PC.COD_FORNECEDOR
INNER JOIN ITEM_PEDIDO_COMPRA IPC ON IPC.COD_PEDIDO_COMPRA = PC.COD_PEDIDO_COMPRA
INNER JOIN PRODUTO P ON P.COD_PRODUTO = IPC.COD_PRODUTO;

-- CONSULTA 5: Recuperar todos os pedidos de venda com informações de cliente e pagamento
SELECT PV.DATA_PEDIDO, PV.VLR_PEDIDO_VENDA, C.NOME AS NOME_CLIENTE, 
       FP.DES_FORMA_PAGAMENTO, SP.STATUS_PEDIDO, SP.STATUS_PAGAMENTO
FROM PEDIDO_VENDA PV
INNER JOIN CLIENTE C ON C.COD_CLIENTE = PV.COD_CLIENTE
INNER JOIN FORMA_PAGAMENTO FP ON FP.COD_FORMA_PAGAMENTO = PV.COD_FORMA_PAGAMENTO
INNER JOIN SITUACAO_PEDIDO SP ON SP.COD_SITUACAO_PEDIDO = PV.COD_SITUACAO_PEDIDO;

-- CONSULTA 6 (LEFT JOIN): Recuperar todos os clientes e seus pedidos (mesmo que não tenham feito nenhum pedido)
SELECT C.NOME AS NOME_CLIENTE, PV.COD_PEDIDO_VENDA
FROM CLIENTE C
LEFT JOIN PEDIDO_VENDA PV ON C.COD_CLIENTE = PV.COD_CLIENTE;

-- CONSULTA 7 (RIGHT JOIN): Recuperar todos os pedidos e seus clientes (incluindo pedidos sem clientes)
SELECT PV.COD_PEDIDO_VENDA, C.NOME AS NOME_CLIENTE
FROM PEDIDO_VENDA PV
RIGHT JOIN CLIENTE C ON C.COD_CLIENTE = PV.COD_CLIENTE;